#pragma once

// Platform defines
#define CORE_PLATFORM(X)					CORE_PLATFORM_PRIVATE_##X()
#define CORE_PLATFORM_PRIVATE_PC()			CORE_BFF_PLATFORM_PRIVATE_PC

// Build config defines
#define CORE_CONFIG(X)						CORE_CONFIG_PRIVATE_##X()
#define CORE_CONFIG_PRIVATE_DEBUG()			CORE_BFF_CONFIG_PRIVATE_DEBUG
#define CORE_CONFIG_PRIVATE_RELEASE()		CORE_BFF_CONFIG_PRIVATE_RELEASE

// Render API defines
#define CORE_RENDER_API(X)					CORE_RENDER_API_PRIVATE_##X()
#define CORE_RENDER_API_PRIVATE_DX11()		CORE_BFF_RENDER_API_PRIVATE_DX11
#define CORE_RENDER_API_PRIVATE_DX12()		CORE_BFF_RENDER_API_PRIVATE_DX12

// Build type defines
#define CORE_BUILD_TYPE(X)					CORE_BUILD_TYPE_PRIVATE_##X()
#define CORE_BUILD_TYPE_PRIVATE_TOOLS()		CORE_BFF_BUILD_TYPE_PRIVATE_TOOLS

// Debug enables
#define CORE_DEBUG_ENABLE(X)				CORE_DEBUG_ENABLE_PRIVATE_##X()
#define CORE_DEBUG_ENABLE_PRIVATE_IMGUI()	CORE_BFF_DEBUG_ENABLE_PRIVATE_IMGUI
