#pragma once

#include "NGA/NGADefs.h"

#if CORE_RENDER_API(DX11)
#include <d3d11.h>
#elif CORE_RENDER_API(DX12)
#include <d3d12.h>
#endif

namespace playground
{
	enum class NGAPrimitiveTopology
	{
#if CORE_RENDER_API(DX11)
		TRIANGLE_LIST = D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST
#elif CORE_RENDER_API(DX12)
		TRIANGLE_LIST = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST
#endif
	};

	enum class NGACullMode
	{
#if CORE_RENDER_API(DX11)
		CULL_NONE = D3D11_CULL_NONE,
		CULL_BACK = D3D11_CULL_BACK,
		CULL_FRONT = D3D11_CULL_FRONT
#elif CORE_RENDER_API(DX12)
		CULL_NONE = D3D12_CULL_MODE_NONE,
		CULL_BACK = D3D12_CULL_MODE_BACK,
		CULL_FRONT = D3D12_CULL_MODE_FRONT
#endif
	};

	enum class NGAFillMode
	{
#if CORE_RENDER_API(DX11)
		SOLID = D3D11_FILL_SOLID,
		WIREFRAME = D3D11_FILL_WIREFRAME
#elif CORE_RENDER_API(DX12)
		SOLID = D3D12_FILL_MODE_SOLID,
		WIREFRAME = D3D12_FILL_MODE_WIREFRAME
#endif
	};

	enum class NGADepthFunc
	{
#if CORE_RENDER_API(DX11)
		NEVER = D3D11_COMPARISON_NEVER,
		ALWAYS = D3D11_COMPARISON_ALWAYS,
		EQUAL = D3D11_COMPARISON_EQUAL,
		NOT_EQUAL = D3D11_COMPARISON_NOT_EQUAL,
		LESS = D3D11_COMPARISON_LESS,
		LESS_EQUAL = D3D11_COMPARISON_LESS_EQUAL,
		GREATER = D3D11_COMPARISON_GREATER,
		GREATER_EQUAL = D3D11_COMPARISON_GREATER_EQUAL,
#elif CORE_RENDER_API(DX12)
		NEVER = D3D12_COMPARISON_FUNC_NEVER,
		ALWAYS = D3D12_COMPARISON_FUNC_ALWAYS,
		EQUAL = D3D12_COMPARISON_FUNC_EQUAL,
		NOT_EQUAL = D3D12_COMPARISON_FUNC_NOT_EQUAL,
		LESS = D3D12_COMPARISON_FUNC_LESS,
		LESS_EQUAL = D3D12_COMPARISON_FUNC_LESS_EQUAL,
		GREATER = D3D12_COMPARISON_FUNC_GREATER,
		GREATER_EQUAL = D3D12_COMPARISON_FUNC_GREATER_EQUAL,
#endif
	};
}